"""
db.py — SQLite conversation logging for the Pura Support Agent

Each conversation turn (user message and agent response) is written as a row
after the stream completes — never during — so logging never blocks the user.

Schema:
    id          INTEGER PRIMARY KEY AUTOINCREMENT
    session_id  TEXT     — UUID generated by the frontend per conversation
    timestamp   TEXT     — ISO 8601 UTC
    role        TEXT     — "user" or "agent"
    message     TEXT     — full message content

The DB file is created automatically on first import if it doesn't exist.
Location is configurable via DB_PATH env var (default: ./data/conversations.db).
"""

import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.getenv("DB_PATH", "./data/conversations.db")

CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS conversations (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT    NOT NULL,
    timestamp  TEXT    NOT NULL,
    role       TEXT    NOT NULL CHECK(role IN ('user', 'agent')),
    message    TEXT    NOT NULL
)
"""


def _connect() -> sqlite3.Connection:
    """Open a connection, creating the DB file and parent directories if needed."""
    Path(DB_PATH).parent.mkdir(parents=True, exist_ok=True)
    return sqlite3.connect(DB_PATH)


def init_db() -> None:
    """Create the conversations table if it does not already exist."""
    with _connect() as conn:
        conn.execute(CREATE_TABLE_SQL)


def log_turn(session_id: str, role: str, message: str) -> None:
    """Write one conversation turn to the database.

    Args:
        session_id: UUID identifying the conversation (generated by frontend).
        role:       "user" or "agent".
        message:    Full text of the message.
    """
    timestamp = datetime.now(timezone.utc).isoformat()
    with _connect() as conn:
        conn.execute(
            "INSERT INTO conversations (session_id, timestamp, role, message) VALUES (?, ?, ?, ?)",
            (session_id, timestamp, role, message),
        )


# Initialise on import so main.py doesn't need to call init_db() explicitly
init_db()
